name: 'build tests'

on:
    pull_request:
        branches: master
    # Please, always create a pull request instead of push to master.
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build dockerfile and Run (without push)
          run: |
            docker build \
            --tag comment9:latest \
            --file ./Dockerfile .
            chmod +x scripts/test-docker.sh
            scripts/test-docker.sh